services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html:delegated
    environment:
      # Nouvelle URL de base de données pour MariaDB
      DATABASE_URL: mysql://symfony:symfony@database:3306/symfony?serverVersion=10.11&charset=utf8mb4
      APP_ENV: dev

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8003:80"
    volumes:
      - .:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  database:
    image: mariadb:10.11 # Changement ici : utilisation de l'image MariaDB
    command: --default-authentication-plugin=mysql_native_password # Recommandé pour certaines versions de MariaDB/PHP
    environment:
      MYSQL_DATABASE: symfony    # Nom de la base de données
      MYSQL_USER: symfony        # Nom d'utilisateur
      MYSQL_PASSWORD: symfony    # Mot de passe
      MYSQL_ROOT_PASSWORD: root  # Mot de passe pour l'utilisateur root
    volumes:
      - db_data:/var/lib/mysql # Chemin du volume persistant pour MariaDB (différent de PostgreSQL)
    ports:
      - "3306:3306" # Mappe le port 3306 pour l'accès direct si besoin (optionnel, mais utile pour des outils comme DBeaver)

volumes:
  db_data: